---
name: ci
on:
  pull_request:
jobs:
  ci_job:
    name: test
    runs-on: ubuntu-24.04
    container:
      image: golang:1.25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: go test -count=1 -v -short -race -timeout 30s ./...
